ci: use micromamba (#1648)
* ci: cache conda env

* fix directory

* fix caching of compilation

* cache pkgs

* skip cache env

* add pip to cache and include python version number

* enable install phase

* capture more deps in conda

* faster install using explicit env file

* touch on windows as well

* give id to cache step

* only save env on no cache hit

* correct yaml file

* get caching working for appveyor

* use micromamba

* make micromamba happy

* make micromamba happy

* make it work with micromamba

* make it work with micromamba

* trail and error

* trail and error

* trail and error

* trail and error

* without script

* make it work with micromamba

* not using conda

* easier dummy

* micromamba upgrade not working on windows?

* disable all

* dummy that works for windows

* do not cache packages

* debug info

* run test

* reset cache

* use checkout v2

* ok to fail

* trail and error

* signle command

* skip test

* install vaex

* activate

* cache packages

* Cleanup packages

* install micromamba first

* use micromamba in install phase

* get dummpy file

* Wget fix

* parallel execution of notebooks

* use feature of new micromamba

* no mamba

* no need to activate

* no need to activate

* simplify, no cache

* undo disabling of tests

* cleanup

* sigh

* no need with micromamba

* remove 1 channel

* conda root to shm

* change channel order

* upgrade scipy dask

* upgrade with um

* update

* downgrade scipy

* different constraint way

* no scipy restriction

* revert more

* revert more (channels)

* nest asyncio fix, no use of pip/pypi

* fix yaml

* smaller diff

* no main channel

* ci: giving up tensorflow

* ci: disable testing ml notebook due to tensorflow

* test: fix seed in ml test

* install pcre

diff --git a/.github/workflows/pythonpackage.yml b/.github/workflows/pythonpackage.yml
--- a/.github/workflows/pythonpackage.yml
+++ b/.github/workflows/pythonpackage.yml
@@ -18,6 +18,9 @@ defaults:
 
 jobs:
   main:
+    env:
+      CACHE_NUMBER_COMPILE: 5
+      MAMBA_ROOT_PREFIX: /dev/shm/mambaroot
     runs-on: ${{ matrix.os }}
     strategy:
       fail-fast: false
@@ -27,12 +30,16 @@ jobs:
         python-version: [3.7, 3.8, 3.9]
 
     steps:
+    - name: disk space
+      if: ${{ (github.event.pull_request.head.repo.full_name == 'vaexio/vaex') && (matrix.os == 'ubuntu-latest') }}
+      run: |
+        df -h
     - uses: maxim-lobanov/setup-xcode@v1
       # alternative would be to upgrade tapi to 1100.0.11, we can possibly remove this in the future
       if: matrix.os == 'macOS-latest'
       with:
         xcode-version: "11.7.0"
-    - uses: actions/checkout@v1
+    - uses: actions/checkout@v2
       with:
         submodules: true
     - uses: actions/checkout@v2
@@ -41,38 +48,32 @@ jobs:
         repository: vaexio/vaex-enterprise
         token: ${{ secrets.PAT_PULL_ENTERPRISE }}
         path: vaex-enterprise
-    - name: Install conda with Python ${{ matrix.python-version }}
-      uses: conda-incubator/setup-miniconda@v2
+    - name: install micromamba
+      uses: mamba-org/provision-with-micromamba@main
       with:
-        python-version: ${{ matrix.python-version }}
-        mamba-version: "*"
-        auto-activate-base: true
-        channels: conda-forge
-    - name: Conda init
-      run: |
-        conda init bash
-    - name: Create env (with mamba)
-      run: |
-        ./ci/02-create-vaex-dev-env.sh ${{ matrix.python-version }} mamba
+        environment-name: vaex-dev
+        environment-file: ci/conda-env.yml
+        extra-specs: |
+            python=${{ matrix.python-version }}
     - name: Extra non-windows installs
       if: matrix.os != 'windows-latest'
       run: |
-        conda activate vaex-dev
         echo "not needed for now"
-    - name: Extra windows installs
-      if: matrix.os == 'windows-latest'
-      run: |
-        conda activate vaex-dev
-        mamba upgrade scipy ipython dask
-        # not sure why, but the conda env is strange (old dask) if we put this constraint in the conda solver
-    - name: free disk space
-      if: matrix.os == 'ubuntu-latest'
-      run: |
-        sudo swapoff -a
-        sudo rm -f /swapfile
-        sudo apt clean
-        docker rmi $(docker image ls -aq)
-        df -h
+    # - name: Extra windows installs
+    #   if: matrix.os == 'windows-latest'
+    #   run: |
+    #     # not sure why, but the conda env is strange (old dask) if we put this constraint in the conda solver
+    #     # also might solve scipy issues
+    #     micromamba update scipy ipython dask
+    #     micromamba install scipy=1.7.1
+    # - name: free disk space
+    #   if: matrix.os == 'ubuntu-latest'
+    #   run: |
+    #     sudo swapoff -a
+    #     sudo rm -f /swapfile
+    #     sudo apt clean
+    #     docker rmi $(docker image ls -aq)
+    #     df -h
     - name: Install OpenMP runtime (Mac-only)
       if: matrix.os == 'macOS-latest'
       run: |
@@ -83,29 +84,32 @@ jobs:
       id: cache-compiled-binaries
       uses: actions/cache@v2
       with:
-        path: packages/vaex-core/build/temp*
-        key: ${{ runner.OS }}-${{ matrix.python-version }}-${{ hashFiles('packages/vaex-core/src/*') }}-v2
+        path: |
+          packages/vaex-core/build/lib*/vaex/vaexfast*
+          packages/vaex-core/build/lib*/vaex/super*
+        key: ${{ runner.OS }}-${{ matrix.python-version }}-${{ hashFiles('packages/vaex-core/src/*') }}-${{ env.CACHE_NUMBER_COMPILE }}
     - name: Fix cache timestamp
-      if: steps.cache-compiled-binaries.outputs.cache-hit == 'true' && matrix.os != 'windows-latest'
       run: |
-        find packages/vaex-core/build -type f -exec touch {} +
+        touch packages/vaex-core/build/lib*/vaex/vaexfast* || echo "ok to fail"
+        touch packages/vaex-core/build/lib*/vaex/super* || echo "ok to fail"
+        ls -alh packages/vaex-core/build/lib*/vaex/ || echo "ok to fail"
     - name: Install vaex
       run: |
-        ./ci/03-install-vaex.sh
-    # - name: Install vaex-enterprise
-    #   if: ${{ (github.event.pull_request.head.repo.full_name == 'vaexio/vaex') && (matrix.os == 'ubuntu-latest') }}
-    #   run: |
-    #     conda activate vaex-dev
-    #     cd vaex-enterprise
-    #     mamba install -c conda-forge distributed
-    #     pip install ray
-    #     pip install -e .
+        pip install myst_parser
+        pip install -e . -v
+        # ./ci/03-install-vaex.sh micromamba
+#    - name: Install vaex-enterprise
+#      if: ${{ (github.event.pull_request.head.repo.full_name == 'vaexio/vaex') && (matrix.os == 'ubuntu-latest') }}
+#      run: |
+#        cd vaex-enterprise
+#        micromamba install -c conda-forge distributed
+#        pip install ray
+#        pip install -e .
     - name: Copy dll
       if: (matrix.os == 'windows-latest')
       uses: ./ci/actions/windll
     - name: Build Python packages
       run: |
-        conda activate vaex-dev
         mkdir dist
         (cd packages/vaex-core && python setup.py bdist_wheel); cp packages/vaex-core/dist/* dist
         (cd packages/vaex-graphql && python setup.py bdist_wheel); cp packages/vaex-graphql/dist/* dist
@@ -121,14 +125,14 @@ jobs:
       with:
         name: dist-${{ github.run_number }}-${{ matrix.python-version }}-${{ matrix.os }}
         path: ./dist
-    - name: Lint with flake8
-      run: |
-        echo "soon"
-        # pip install flake8
-        # stop the build if there are Python syntax errors or undefined names
-        # flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
-        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
-        # flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
+    # - name: Lint with flake8
+    #   run: |
+    #     echo "soon"
+    #     # pip install flake8
+    #     # stop the build if there are Python syntax errors or undefined names
+    #     # flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
+    #     # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
+    #     # flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
     - name: Test with pytest
       run: |
         ./ci/04-run-test-suite.sh
@@ -140,14 +144,12 @@ jobs:
       # no catboost for py39 and py37
       if: matrix.python-version != '3.9' && matrix.os != 'windows-latest' && matrix.python-version != '3.7'
       run: |
-        conda activate vaex-dev
         python -m vaex.ml.spec packages/vaex-ml/vaex/ml/spec_new.json
         diff packages/vaex-ml/vaex/ml/spec_new.json packages/vaex-ml/vaex/ml/spec.json
-    # - name: Test with pytest (vaex-enterprise)
-    #   if: ${{ (github.event.pull_request.head.repo.full_name == 'vaexio/vaex') && (matrix.os == 'ubuntu-latest') }}
-    #   run: |
-    #     conda activate vaex-dev
-    #     py.test vaex-enterprise/tests --timeout=1000
+#    - name: Test with pytest (vaex-enterprise)
+#      if: ${{ (github.event.pull_request.head.repo.full_name == 'vaexio/vaex') && (matrix.os == 'ubuntu-latest') }}
+#      run: |
+#        py.test vaex-enterprise/tests --timeout=1000
     - name: Test notebooks
       if: matrix.os != 'windows-latest'
       run: |
@@ -164,7 +166,6 @@ jobs:
       env:
         PROJECT_ID: ${{ secrets.GCP_PROJECT_ID_VAEX }}
       run: |
-        conda activate vaex-dev
         pip install -e 'packages/vaex-contrib[gcp]'
         ./ci/06-run-contrib-tests.sh
 
@@ -183,19 +184,31 @@ jobs:
             python-version: 3.7
 
     steps:
+    - uses: actions/checkout@v2
     - uses: actions/download-artifact@v2
       with:
         name: dist-${{ github.run_number }}-${{ matrix.python-version }}-${{ matrix.os }}
         path: ./dist
 
-    - name: Install conda with Python ${{ matrix.python-version }}
-      uses: conda-incubator/setup-miniconda@v2
+    - name: Install micromamba
+      uses: mamba-org/provision-with-micromamba@main
       with:
-        python-version: ${{ matrix.python-version }}
-        mamba-version: "*"
-        auto-activate-base: true
-        auto-update-conda: true
-        channels: conda-forge
+        environment-name: vaex-test
+        environment-file: ci/conda-base-minimal.yml
+        extra-specs: |
+            python=${{ matrix.python-version }}
+            pcre
+    # it shouldn't be needed to use pcre, maybe we should make the wheels similar to how we make distributions
+    - name: Cache pip
+      uses: actions/cache@v2
+      env:
+        # Increase this value to reset cache
+        CACHE_NUMBER: 0
+      with:
+        path: |
+          ~/.cache/pip
+        key:
+          pip-${{ runner.os }}-${{ matrix.python-version }}-${{ env.CACHE_NUMBER }}
 
     - name: Install the packages
       run: |
